run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gofmt
    - goimports
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  gocritic:
    enabled-checks:
      - dupImport
      - ifElseChain
      - nestingReduce
      - truncateCmp
      - unnamedResult

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
